### ISSUE TITLE
Write unit tests for the functions

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-utilities#2] opened 2023-05-24 19:14 UTC

**Comment by robertdevine** [comment] 2024-01-24 21:37
[QC_FINDINGS_CONFIRMATION_SUMMARY_REPORT_USING_expect_dfs_equals.txt](https://github.com/RConsortium/submissions-pilot3-utilities/files/14090429/QC_FINDINGS_CONFIRMATION_SUMMARY_REPORT_USING_expect_dfs_equals.txt)

@bms63 and @laxamanaj, appropriate to develop the unit tests for the functions using the admiraldev reference [here](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#test-coverage). PR should get issued sometime next week for review. Chipping away at the remaining issues so everything is in good order for when Regulatory Reviewers issue their Pilot3 Review and Report. thx.

![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/8195239/acd04aaf-200a-4077-98c9-d76e3f3fd5ed)

The testthat( ) automation may be helpful for Pilot3 as well. Also, testing the {admiral} functions (interested to unit test the LOCF derivation flagged by the regulatory review). The {admiraldev} function [expect_dfs_equal](https://pharmaverse.github.io/admiraldev/reference/expect_dfs_equal.html) is helpful.

Using the {admiraldev} function to test FDA Review Observation [here](https://rconsortium.github.io/submissions-wg/minutes/2024-01-05/), per the cited discrepancies in 'primary output' from [Pilot1](https://github.com/RConsortium/submissions-pilot1-to-fda/blob/main/m1/us/report-tlf.pdf) and [Pilot3](https://github.com/RConsortium/submissions-pilot3-adam/blob/main/submission/output/tlf-primary-pilot3.rtf.pdf).

Per Pilot3 [QC Findings](https://github.com/RConsortium/submissions-pilot3-adam/wiki/QC-Findings), "_**The R-generated ADADAS matches original adadas from CDISC pilot data, except for the records where PARAMCD=ACTOT, DTYPE=LOCF. This is an issue from the CDISC ADADAS.**_" Testing with {admiraldev} unit test functions to re-confirm. (@laxamanaj, @kaz462, @bms63) 

Unit testing does confirm the **QC Findings** conclusion concerning the discrepancies cited by _FDA Reviewers_. The confirmation is demonstrated using the _expect_dfs_equal_( ) {admiraldev} unit test. (Output report attached - verbose)

To generate a full report, please issue the command below from console or within expect statement using testthat:
     >**try(expect_dfs_equal(adadas, qc_adadas, keys = c("USUBJID", "PARAMCD", "AVISIT", "ADT")))** 

![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/8195239/fc940fba-85a7-4f99-b53d-b6f6ef3fa96a)

With testthat( ), Pilot3 Team provides _systematic testing_ so if anyone wants to modify functional codes then the package automatically catches breaking changes - quality checks, downstream dependency safety checks, data integrity, as discussed by the WG. We'll drop in ~100 unit tests covering each function across the R source files in _pilot3utils_. The {admiraldev} unit tests should be helpful. Using tibble[::tribble] samples from the _Subject-Level Analysis Dataset_ to unit test Tplyr-helper functions (e.g. **nest_rowlabels**, **bind_rows**) and helper functions (e.g. **pad_row**, **num_fmt**). thx. 

![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/8195239/22fbe8da-74b9-4fe5-88c3-08bde8994b9b)

**Comment by bms63** [comment] 2024-01-24 22:03
oh that would be pretty cool!!

**Comment by laxamanaj** [comment] 2024-01-25 18:10
Thanks, @robertdevine !

**Comment by robertdevine** [comment] 2024-01-29 22:45
@laxamanaj, @bms63, @kaz462 - we pretty much have the pilot3 **testthat**( ) unit tests completed including a confirmation test using '_expect_dfs_equal_( )' to support the **QC Findings** conclusion and address the _FDA Reviewers_ observations regarding primary output _discrepancies_ between pilot1 and pilot3. We have good test coverage over the _pilot3utilities_ functions. Will issue PR later this week. thx.

@kaz462 - unit testing does replicate the **[QC Findings](https://github.com/RConsortium/submissions-pilot3-adam/wiki/QC-Findings)** at each step in the ADADAS section of the Pilot3 document - the '_**expect_dfs_equa**l_( )' function generates a nearly identical summary report (attached - verbose) to **diffdf**( ) when comparing 'adadas' and 'qc_adadas'. Thank you again.

**Comment by robertdevine** [comment] 2024-02-01 17:02
@laxamanaj, @bms63 - the unit testing in Pilot3 also appears to be a community contribution for a sample of efficacy functionality from the [CDISC Pilot Replication](https://github.com/atorus-research/CDISC_pilot_replication/tree/3c8e9e3798c02be8d93bd8e8944d1e0d3f6519e2) PHUSE Test Data Factory ADaM data, using the R programming language repository. Many thanks to CDISC Pilot replication for providing the functions. Pretty cool to see the community collaboration with ADaM data. thx.

**Comment by bms63** [comment] 2024-02-01 20:56
Awesome @robertdevine looking forward to reviewing.  It would be nice for our package to be a little snazzier when we re-submit.  Felt a little janky when submitted in the Fall!!

**Comment by bms63** [comment] 2024-02-09 01:37
Hey Robert - just checking on timeline for this?  I don't see a separate branch for this - is this being done locally? We want to re-submit soon, let me know if you need some help on finish this out.  Many thanks again!!

**Comment by robertdevine** [comment] 2024-02-09 14:00
Hi @bms63, adding tests to include coverage with latest unmerged changes from PR Issue [#146](https://github.com/RConsortium/submissions-pilot3-adam/pull/146#issuecomment-1935193445) yesterday, should be able to push later today or latest on Monday using local branch _pilot3utils-unit-tests_ per the screenshots above. Test coverage approaches 100%. thx.

@bms63, @laxamanaj - as far as timeline for this Issue [#2](https://github.com/RConsortium/submissions-pilot3-utilities/issues/2) unit tests for pilot3utils, the issue is tracked on the Pilot3 [project board] https://github.com/orgs/RConsortium/projects/7/views/1) as '_In Progress_' since January 26, 2024. The API for the repo does not appear enabled to return query parameters for timeline events. The Pilot3 issue timeline events are not parameterized with the GH REST API feature to track timeline events for tracking issue timelines, just the project board without the event triggers. If you run a query the response is empty. (below) thx. 

![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/8195239/bd43aa84-1580-4612-8856-bd6e28cf37ef)

@bms63, @laxamanaj - actually collaborator access to the _submissions-pilot3-utilities_ repository is needed for me to push the automated unit test codes. Collaborator access is granted through Collaborators tab under Settings. thx.

![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/8195239/ee6df69f-83ac-4e8d-9dd6-066eea52812b)

The unit tests are run in automation from developer's console at any time by issuing the command sequence: 
**CTRL+SHIFT+L** followed by **CTRL+SHIFT+T**  [i.e. Essentially, LOAD ALL+TEST]

We also ran _**test_check**_( ) [0 Errors 0 Warnings 1 Note] which runs correctly for the package in under one minute.

![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/8195239/45752b19-a708-415b-867b-b373e0717552)

Having the systematic testing built into the workflow does assist the developer experience while building out _pilot3utils_ package - i.e. protects against downstream dependency breaking changes, etc.. Overall, pretty cool. thx.

*The additional test coverage to include _**derive_locf_records**_( ) function is due to discrepancies noted by FDA Reviewers [here](https://rconsortium.github.io/submissions-pilot3-adam/main/articles/feedback_jan2024.html) (please see **Item 2** on the document) and addressed in [QC Findings](https://github.com/RConsortium/submissions-pilot3-adam/wiki/QC-Findings) under the ADADAS section. thx.

**Nice to have would be to address the NOTE with additional systematic checks for the suggested but not required here.

**Comment by robertdevine** [comment] 2024-02-12 20:03
@laxamanaj, @bms63, @kaz462 - for the {admiral} functions [like derive_locf_records} the unit testing with the testthat( ) 
uses a pattern of **namespace**::**function**( ) notation when testing the ADaM data sets etc. within _pilot3utils_ package 
automated testing. thx.

![image](https://github.com/RConsortium/submissions-pilot3-utilities/assets/8195239/ec4b564a-9f07-47d6-833d-7fca160a1c4a)

**Comment by bms63** [comment] 2024-02-13 15:48
Thanks Robert!  Let me know when the PR is ready and we can merge it in ASAP.

Wondering...Do we need the `derive_var_locf` function anymore in `pilot3utils`?  I was under the impression that admiral had incorporated this change - @kaz462 can you confirm.

**Comment by robertdevine** [comment] 2024-02-13 16:11
@bms63 - actually collaborator access to the submissions-pilot3-utilities repository is needed for me to push the automated unit test codes. Collaborator access is granted through Collaborators tab under Settings. thx.

**Comment by bms63** [comment] 2024-02-13 16:17
> @bms63 - actually collaborator access to the submissions-pilot3-utilities repository is needed for me to push the automated unit test codes. Collaborator access is granted through Collaborators tab under Settings. thx.

Added you in

Thanks @bms63, added a branch for this issue and will create PR using the issue branch today.

**Comment by kaz462** [comment] 2024-02-13 17:16
> Wondering...Do we need the `derive_var_locf` function anymore in `pilot3utils`? I was under the impression that admiral had incorporated this change - @kaz462 can you confirm.

@bms63 you are right, this was incorporated in admiral, so we don't need `derive_var_locf` in `pilot3utils`

@bms63, @kaz462 - The {admiral} test coverage is excellent - 680+ unit tests using testthat( ) - [here](https://github.com/pharmaverse/admiral/blob/main/tests/testthat/test-derive_locf_records.R). thx.

**Comment by bms63** [comment] 2024-02-13 17:53
@robertdevine can you remove the pilot3utils function and test in this branch/PR for us?

@bms63 - will do. thx.

**Comment by robertdevine** [comment] 2024-02-28 19:11
Please see discussion [here](https://github.com/RConsortium/submissions-pilot3-adam/issues/161#issuecomment-1962481778). Then we'll wrap this up and have test coverage over R/user_utils.R as well since they were used earlier in the pilot3 but not explicitly in _pilot3utils_. package thx.

**Closed as completed** 2024-02-29 17:41 UTC
Labels: enhancement
